name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Generate image tag
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Login to GHCR
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u zalan0815 --password-stdin

    - name: Build backend
      run: |
        docker build ./backend --file ./backend/Dockerfile \
        --tag ghcr.io/zalan0815/k8s_beadando-backend:$IMAGE_TAG

    - name: Push backend
      run: |
        docker push ghcr.io/zalan0815/k8s_beadando-backend:$IMAGE_TAG

    - name: Build frontend
      run: |
        docker build ./frontend --file ./frontend/Dockerfile \
        --tag ghcr.io/zalan0815/k8s_beadando-frontend:$IMAGE_TAG

    - name: Push frontend
      run: |
        docker push ghcr.io/zalan0815/k8s_beadando-frontend:$IMAGE_TAG

    - name: Update deployment.yaml
      run: |
        sed -i 's|ghcr.io/zalan0815/k8s_beadando-backend:.*|ghcr.io/zalan0815/k8s_beadando-backend:'"$IMAGE_TAG"'|' deployment.yaml

        sed -i 's|ghcr.io/zalan0815/k8s_beadando-frontend:.*|ghcr.io/zalan0815/k8s_beadando-frontend:'"$IMAGE_TAG"'|' deployment.yaml

    - name: Commit changes
      run: |
        git config --global user.name "zalan0815"
        git config --global user.email "zalan0815@users.noreply.github.com"
        git add deployment.yaml
        git commit -m "update k8s images" || echo "no changes"
        git push